#!usr/bin/env python
import termcolor

print(" ")
print(termcolor.colored("The ",'red'))
print(termcolor.colored("██╗  ██╗██╗   ██╗███╗  ██╗████████╗███████╗██████╗ ",'red'))
print(termcolor.colored("██║  ██║██║   ██║████╗ ██║╚══██╔══╝██╔════╝██╔══██╗",'red'))
print(termcolor.colored("███████║██║   ██║██╔██╗██║   ██║   █████╗  ██████╔╝",'red'))
print(termcolor.colored("██╔══██║██║   ██║██║╚████║   ██║   ██╔══╝  ██╔══██╗",'red'))
print(termcolor.colored("██║  ██║╚██████╔╝██║ ╚███║   ██║   ███████╗██║  ██║",'red'))
print(termcolor.colored("╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚══╝   ╚═╝   ╚══════╝╚═╝  ╚═╝ Script V1.0",'red'))
print(" ")

print("Note:This is a beta version of the tool")
print("Developed By: @gsvprharsha(github), @Yash, @Disha, @Ankit")
print(" ")
print("<------------------------------------------------------------>")
print("\t\t\tAvailable Tools")
print(" ")
print("1.MAC Changer\t\t\t\t\t3.ARP Spoofer")
print("2.Network Scanner\t\t\t\t4.Packet Sniffer")
print(" ")
print("Press 0 to exit ")
print(" ")
option = input("Choose an option: ")
